// JSON import for the DSR → Schedule page.
//
// Lets the user paste JSON extracted by a vision AI model (from a scanned or
// digital Schedule of Work) straight into the app. Expected shape:
//   { standard_items: [{s_no, type:"DSR", dsr_code, description, quantity, unit, rate}],
//     special_items:  [{s_no, type:"MKT"|"Appd.", description, quantity, unit, rate}] }
//
// standard_items are matched against the DSR database — reusing the OCR
// import's dot-tolerant digit-signature matcher — and the DB's own
// description/unit/rate win over whatever the vision model read. special_items
// have no DB row, so their description/unit/rate are taken from the JSON
// as-is. Every item keeps the sheet's own s_no, and the merged result is
// sorted by it so the schedule comes out in the same order as the source
// document (standard + special items interleaved exactly as printed).

import { matchCode } from './ocr.js';
import { search } from './data.js';

// ---------------------------------------------------------------------------
// Lenient JSON parsing — vision models sometimes wrap output in ```json
// fences despite instructions not to; strip that before parsing.
function stripFences(text) {
  let t = String(text == null ? '' : text).trim();
  t = t.replace(/^```[a-zA-Z]*\s*/, '').replace(/```\s*$/, '');
  return t.trim();
}

function parseLenientJson(text) {
  const cleaned = stripFences(text);
  if (!cleaned) throw new Error('Paste the JSON generated by your vision model first.');
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    throw new Error(`Could not parse that as JSON: ${e.message}`);
  }
}

// ---------------------------------------------------------------------------
// s_no ordering — "5" < "6" < "12"; a trailing letter ("5A") sorts right
// after its bare number. Falls back to a plain string compare otherwise.
function snoCompare(a, b) {
  const ma = /^\s*(\d+(?:\.\d+)?)?\s*(.*)$/.exec(String(a ?? '')) || [];
  const mb = /^\s*(\d+(?:\.\d+)?)?\s*(.*)$/.exec(String(b ?? '')) || [];
  const na = ma[1] !== undefined ? parseFloat(ma[1]) : NaN;
  const nb = mb[1] !== undefined ? parseFloat(mb[1]) : NaN;
  const aNum = !isNaN(na), bNum = !isNaN(nb);
  if (aNum && bNum && na !== nb) return na - nb;
  if (aNum && !bNum) return -1;
  if (!aNum && bNum) return 1;
  return String(ma[2] || '').localeCompare(String(mb[2] || ''));
}

// ---------------------------------------------------------------------------
// Match a standard (DSR) item against the database. When a code is given,
// defer entirely to the OCR matcher's dot-tolerant digit-signature logic
// (exact / fuzzy-neighbor / description-tiebreak, in that order). When the
// vision model couldn't read a code at all (dsr_code: null, blank, or text
// with no digits at all), match purely by description.
function matchStandardItem(dsrCode, description) {
  const code = String(dsrCode == null ? '' : dsrCode).trim();
  if (code && /\d/.test(code)) return matchCode(code, description);
  const cands = search(description || '', 5);
  if (!cands.length) return { status: 'notfound', code, item: null, confidence: 0, candidates: [] };
  return { status: 'guess', code: cands[0].code, item: cands[0], confidence: 0.3, candidates: cands };
}

const toNum = (v) => {
  if (v === null || v === undefined || v === '') return null;
  const n = typeof v === 'number' ? v : parseFloat(String(v).replace(/,/g, ''));
  return isFinite(n) ? n : null;
};
const numStr = (n) => (n == null ? '' : String(n));
const strOf = (v) => (v == null ? '' : String(v));

function normalizeStandard(item, i, warnings) {
  const s_no = strOf(item?.s_no);
  if (!s_no) warnings.push(`standard_items[${i}]: missing s_no`);
  const type = strOf(item?.type).trim();
  if (type !== 'DSR') warnings.push(`standard_items[${i}] (s_no ${s_no || i + 1}): type is "${item?.type}", expected "DSR"`);
  const quantity = toNum(item?.quantity);
  if (quantity == null) warnings.push(`standard_items[${i}] (s_no ${s_no || i + 1}): missing or invalid quantity`);
  return {
    kind: 'standard', s_no,
    dsr_code: item?.dsr_code != null ? String(item.dsr_code).trim() : '',
    description: strOf(item?.description),
    quantity, unit: strOf(item?.unit), rate: toNum(item?.rate),
  };
}

function normalizeSpecial(item, i, warnings) {
  const s_no = strOf(item?.s_no);
  if (!s_no) warnings.push(`special_items[${i}]: missing s_no`);
  let type = strOf(item?.type).trim();
  if (type !== 'MKT' && type !== 'Appd.') {
    warnings.push(`special_items[${i}] (s_no ${s_no || i + 1}): type is "${item?.type}", expected "MKT" or "Appd." — treated as Appd.`);
    type = 'Appd.';
  }
  const quantity = toNum(item?.quantity);
  if (quantity == null) warnings.push(`special_items[${i}] (s_no ${s_no || i + 1}): missing or invalid quantity`);
  return {
    kind: 'special', s_no, type,
    description: strOf(item?.description),
    quantity, unit: strOf(item?.unit), rate: toNum(item?.rate),
  };
}

function buildRow(r, i) {
  const base = { id: `json-${i}`, s_no: r.s_no, qty: numStr(r.quantity), carriage: false, rateOptions: null };

  if (r.kind === 'standard') {
    const m = matchStandardItem(r.dsr_code, r.description);
    const row = {
      ...base,
      category: 'DSR',
      code: m.code || r.dsr_code || '',
      match: m.status, confidence: m.confidence, candidates: m.candidates || [],
    };
    if (m.item) {
      row.description = m.item.description;
      row.unit = m.item.unit;
      row.rate = numStr(m.item.rate);
      row.carriage = !!m.item.carriage;
      row.rateOptions = m.item.rate_options || null;
    } else {
      row.description = r.description;
      row.unit = r.unit;
      row.rate = numStr(r.rate);
    }
    return row;
  }

  return {
    ...base,
    category: r.type,
    code: '',
    description: r.description,
    unit: r.unit,
    rate: numStr(r.rate),
    match: 'manual', confidence: 1, candidates: [],
  };
}

// Parse + validate + match a pasted JSON payload (raw text) into review rows,
// ordered exactly as the source sheet's s_no (standard + special interleaved).
export function parseJsonImport(text) {
  const data = parseLenientJson(text);
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    throw new Error('Expected a JSON object with "standard_items" and/or "special_items" arrays.');
  }
  const standard = Array.isArray(data.standard_items) ? data.standard_items : [];
  const special = Array.isArray(data.special_items) ? data.special_items : [];
  if (!standard.length && !special.length) {
    throw new Error('No items found — expected "standard_items" and/or "special_items" arrays.');
  }

  const warnings = [];
  const combined = [
    ...standard.map((it, i) => normalizeStandard(it, i, warnings)),
    ...special.map((it, i) => normalizeSpecial(it, i, warnings)),
  ];
  combined.sort((a, b) => snoCompare(a.s_no, b.s_no));

  const rows = combined.map((r, i) => buildRow(r, i));

  return {
    rows,
    warnings,
    stats: {
      total: rows.length,
      matched: rows.filter((r) => r.match === 'matched').length,
      review: rows.filter((r) => r.match === 'ambiguous' || r.match === 'guess' || r.match === 'notfound').length,
    },
  };
}

// Re-match a single row after the user edits its DSR code/description in review.
export function matchJsonRow(code, description) {
  return matchStandardItem(code, description);
}
