// Tender-details import for the Schedule → Bill page.
//
// The companion to json-import.js: instead of a Schedule of Work, the user
// pastes a vision AI's JSON reading of the DUSIB **award letter / work order**,
// and we fill the Bill Header (+ the quoted rate box) from it. Expected shape
// is documented in TENDER_PROMPT (frontend/src/components/TenderImportModal.jsx)
// — the model transcribes only what is PRINTED on the letter; every derived
// value (dates, formatting, cross-checks) is computed here, never by the model.
//
// The letter carries its own redundancy, and we exploit all of it:
//   • every amount is printed in digits AND in words  → words must equal digits
//   • quoted = estimated × (1 − pct/100)              → the three must agree
// A misread digit breaks at least one of these, so it surfaces in the review
// step instead of on a signed bill.

// ---------------------------------------------------------------------------
// Lenient JSON parsing — same tolerance as json-import.js (models wrap output
// in ```json fences even when told not to).
function stripFences(text) {
  let t = String(text == null ? '' : text).trim();
  t = t.replace(/^```[a-zA-Z]*\s*/, '').replace(/```\s*$/, '');
  return t.trim();
}

function parseLenientJson(text) {
  const cleaned = stripFences(text);
  if (!cleaned) throw new Error('Paste the JSON generated by your vision model first.');
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    throw new Error(`Could not parse that as JSON: ${e.message}`);
  }
}

// ---------------------------------------------------------------------------
// Indian-system words → number, used only to cross-check the digits.
// Deliberately tolerant of the spellings that actually appear on these letters
// ("Fourty", "Ninty") — a real DUSIB award letter prints both, and refusing to
// read them would turn a working cross-check into a permanent false alarm.
const W_UNITS = {
  zero: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7,
  eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12, thirteen: 13,
  fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18,
  nineteen: 19,
};
const W_TENS = {
  twenty: 20, thirty: 30, forty: 40, fourty: 40, fifty: 50, sixty: 60,
  seventy: 70, eighty: 80, ninety: 90, ninty: 90,
};
const W_MULT = { thousand: 1e3, lakh: 1e5, lakhs: 1e5, crore: 1e7, crores: 1e7 };
const W_SKIP = new Set(['and', 'only', 'rupees', 'rupee', 'rs', 'rs.', '/-', 'paise']);

export function wordsToNumber(words) {
  const toks = String(words == null ? '' : words)
    .toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).filter(Boolean);
  if (!toks.length) return null;
  let total = 0, cur = 0, seen = false;
  for (const t of toks) {
    if (W_SKIP.has(t)) continue;
    if (t in W_UNITS) { cur += W_UNITS[t]; seen = true; }
    else if (t in W_TENS) { cur += W_TENS[t]; seen = true; }
    else if (t === 'hundred') { cur = (cur || 1) * 100; seen = true; }
    else if (t in W_MULT) { total += (cur || 1) * W_MULT[t]; cur = 0; seen = true; }
    else return null; // an unknown word — don't guess, just skip the check
  }
  return seen ? total + cur : null;
}

// ---------------------------------------------------------------------------
// Dates. The model gives ISO (YYYY-MM-DD); we format for the sheet and do all
// the arithmetic here.
function parseIso(s) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(s || '').trim());
  if (!m) return null;
  const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]));
  if (isNaN(d.getTime()) || d.getUTCMonth() !== +m[2] - 1) return null;
  return d;
}
function addDays(d, n) {
  const x = new Date(d.getTime());
  x.setUTCDate(x.getUTCDate() + n);
  return x;
}
function fmtDate(d, sep = '.') {
  const p = (n) => String(n).padStart(2, '0');
  return `${p(d.getUTCDate())}${sep}${p(d.getUTCMonth() + 1)}${sep}${d.getUTCFullYear()}`;
}

// Indian grouping, 2 dp — matches the money convention used across the app.
function fmtMoney(n) {
  if (n == null || !isFinite(n)) return '';
  return Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

const str = (v) => (v == null ? '' : String(v).trim());
const numOrNull = (v) => {
  if (v == null || v === '') return null;
  const n = typeof v === 'number' ? v : parseFloat(String(v).replace(/[,\s₹]|Rs\.?/gi, ''));
  return isFinite(n) ? n : null;
};

// ---------------------------------------------------------------------------
// Main entry: JSON text → { meta, rates, dateSuggestion, checks }
export function parseTenderImport(text) {
  const d = parseLenientJson(text);
  if (!d || typeof d !== 'object' || Array.isArray(d)) {
    throw new Error('Expected a JSON object describing the award letter.');
  }

  const letter = d.award_letter || {};
  const agency = d.agency || {};
  const work = d.work || {};
  const amounts = d.amounts || {};
  const time = d.time_allowed || {};

  const letterNo = str(letter.letter_no);
  const letterDate = parseIso(letter.letter_date);
  const quoted = numOrNull(amounts.quoted_amount);
  const estimate = numOrNull(amounts.estimated_cost);
  const pct = numOrNull(amounts.quoted_percent);
  const dirRaw = str(amounts.quoted_direction).toLowerCase();
  const dir = dirRaw === 'above' ? 'above' : 'below';

  const checks = [];
  const ok = (label, detail) => checks.push({ level: 'ok', label, detail });
  const warn = (label, detail) => checks.push({ level: 'warn', label, detail });

  // --- cross-check 1: amount in words vs amount in digits ---
  const wordCheck = (digits, words, label) => {
    const w = wordsToNumber(words);
    if (digits == null) { warn(label, 'no amount in digits was read'); return; }
    if (w == null) return;               // unreadable words — silent, not a failure
    if (Math.abs(w - digits) < 0.5) ok(label, `${fmtMoney(digits)} agrees with "${str(words)}"`);
    else warn(label, `digits say ${fmtMoney(digits)} but the words say ${fmtMoney(w)} ("${str(words)}") — check which is right`);
  };
  wordCheck(quoted, amounts.quoted_amount_words, 'Tender amount');
  wordCheck(estimate, amounts.estimated_cost_words, 'Estimate amount');

  // --- cross-check 2: quoted = estimated × (1 ∓ pct/100) ---
  // The letter states all three, so they must reconcile. Tolerance is 1 rupee
  // (the letter's own figures are rounded to the rupee).
  if (quoted != null && estimate != null && pct != null) {
    const expect = estimate * (dir === 'above' ? 1 + pct / 100 : 1 - pct / 100);
    if (Math.abs(expect - quoted) <= 1.5) {
      ok('Quoted %', `${pct}% ${dir} of ${fmtMoney(estimate)} = ${fmtMoney(expect)} ≈ tender ${fmtMoney(quoted)}`);
    } else {
      warn('Quoted %', `${pct}% ${dir} of ${fmtMoney(estimate)} works out to ${fmtMoney(expect)}, but the tender amount reads ${fmtMoney(quoted)} — one of the three is misread`);
    }
  } else if (pct == null) {
    warn('Quoted %', 'no quoted percentage was read — the Quoted rate % box will stay as it is');
  }

  if (!letterNo) warn('Agreement / Work No.', 'no letter number was read');
  if (!letterDate && str(letter.letter_date)) {
    warn('Letter date', `"${str(letter.letter_date)}" is not a valid YYYY-MM-DD date — left out of the Work No.`);
  }

  // --- header (verbatim from the letter; blank stays blank) ---
  const meta = {
    workName: str(work.scheme_name),
    subHead: str(work.sub_head),
    agency: str(agency.name),
    workNo: letterNo && letterDate ? `${letterNo}, dated: ${fmtDate(letterDate)}` : letterNo,
    tenderAmount: fmtMoney(quoted),
    estimateAmount: fmtMoney(estimate),
  };

  const rates = { quotedPct: pct == null ? null : pct, quotedType: pct == null ? null : dir };

  // --- date suggestion (never auto-applied) ---
  // The letter states a formula ("N days, reckoned from M days after the date of
  // issue"), but the agreement's real dates can differ, so this is only ever
  // offered for the user to accept.
  const days = numOrNull(time.days);
  const offset = numOrNull(time.reckoned_from_days_after_letter);
  let dateSuggestion = null;
  if (letterDate && days != null && offset != null) {
    const start = addDays(letterDate, offset);
    const end = addDays(start, days);
    dateSuggestion = {
      dateStart: fmtDate(start, '/'),
      dateCompletion: fmtDate(end, '/'),
      basis: `letter dated ${fmtDate(letterDate)} + ${offset} days to commence, then ${days} days allowed`,
    };
  }

  return { meta, rates, dateSuggestion, checks };
}
